//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleControl.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BioDataContext : DbContext
    {
        public BioDataContext()
            : base("name=BioDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dept> Dept { get; set; }
        public virtual DbSet<Holiday> Holiday { get; set; }
        public virtual DbSet<Userinfo> Userinfo { get; set; }
        public virtual DbSet<UserLeave> UserLeave { get; set; }
        public virtual DbSet<UserShift> UserShift { get; set; }
        public virtual DbSet<UserTempShift> UserTempShift { get; set; }
        public virtual DbSet<V_Class> V_Class { get; set; }
        public virtual DbSet<V_Record> V_Record { get; set; }
    }
}
