//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleControl.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Record
    {
        public int Logid { get; set; }
        public string Userid { get; set; }
        public System.DateTime CheckTime { get; set; }
        public int CheckType { get; set; }
        public Nullable<int> Sensorid { get; set; }
        public Nullable<int> WorkType { get; set; }
        public Nullable<int> AttFlag { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<bool> Exported { get; set; }
        public Nullable<bool> OpenDoorFlag { get; set; }
        public Nullable<double> temperature { get; set; }
        public Nullable<int> whynoopen { get; set; }
        public Nullable<int> mask { get; set; }
        public string Name { get; set; }
        public Nullable<int> Deptid { get; set; }
        public string usercode { get; set; }
        public string Duty { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> Clientid { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> deviceflag { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusChar { get; set; }
        public string StatusText { get; set; }
    }
}
